# Generated by Django 4.2.27 on 2026-01-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_level', models.IntegerField(default=1)),
                ('consecutive_correct', models.IntegerField(default=0)),
                ('consecutive_incorrect', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('math', 'Math'), ('typing', 'Typing'), ('spelling', 'Spelling')], max_length=10)),
                ('question', models.TextField()),
                ('correct_answer', models.TextField()),
                ('user_answer', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('difficulty_level', models.IntegerField()),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exercises.session')),
            ],
        ),
    ]
